### ISSUE TITLE
Question:  dataset

### ISSUE THREAD

**Issue by zhitm** [zorazrw/filco#2]
Hi, i have a question about what exactly should i do with DPR to get dataset for measure_ctxs.py. I suppose i should run python data/download_data.py \
	--resource {key from download_data.py's RESOURCES_MAP}, but which dataset?

**Comment by zorazrw** [comment]
Hi, thanks for your interest! 

Our experiments used the "checkpoint.retriever.single-adv-hn.nq.bert-base-encoder" retrieval model. You can also download their Wikipedia dump "data.wikipedia_split.psgs_w100" as the retrieval source for all datasets. 
For the experimented datasets, DPR only supports NQ (NaturalQuestions) and TQA (Trivia QA), for which you can download "data.retriever.qas.nq-train/dev/test" and "data.retriever.qas.trivia-train/dev/test".
For the other four datasets, you can download from the KILT benchmark (https://github.com/facebookresearch/KILT) or its huggingface portal (https://huggingface.co/datasets/kilt_tasks).

We also just provided all datasets with the top-5 retrieved passages [here](https://drive.google.com/file/d/13z_qrVOBlgu75IJBpX-1vMSCC6hC9yH4/view?usp=sharing). Hope this solves your issue!

**Comment by zhitm** [comment]
Thank you!
