### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by wyzhhhh** [zorazrw/filco#3]
When executing the first step of measure_ctxs.py, the running time is too long. Is there any way to speed up the running speed?

**Comment by chubzchubz97** [comment]
Same issue. Did you mange to resolve it?

**Comment by zorazrw** [comment]
Hi! This step requires using a neural model so it is expected to take a long time. Nonetheless, the current implementation is not optimized for running time. Several exemplar approaches that may help:
1. add batching of the sentences
2. run this script on multiple shards of the data in parallel
3. change to a smaller model 

I'll try to find time to optimize the code, possibly including the first two points that I mentioned above. In the meantime, feel free to create a PR if you made according modifications and can effectively accelerate this process!
