### ISSUE TITLE
question: about the output in file: /datasets/nq/mctx/em/train_em_top1.json

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [zorazrw/filco#4]
I run the get_inputs.py program on the nq data set on the context filtering task, but I find that after running the result, the corresponding output is empty. Is this correct? I understand that the output of this step should be the filtered text, but I have nothing here. Here is an example:
`[{"input": "Given the ['question', 'context'], predict the most helpful sentence in the context.\n\nquestion: who got the first nobel prize in physics\ncontext: Nobel Prize in Physics The Nobel Prize in Physics () is a yearly award given by the Royal Swedish Academy of Sciences for those who have made the most outstanding contributions for mankind in the field of physics. It is one of the five Nobel Prizes established by the will of Alfred Nobel in 1895 and awarded since 1901; the others being the Nobel Prize in Chemistry, Nobel Prize in Literature, Nobel Peace Prize, and Nobel Prize in Physiology or Medicine. The first Nobel Prize in Physics was awarded to physicist Wilhelm R\u00f6ntgen in recognition of the extraordinary services he", **"output": ""**}`

I wonder if this is normal and if you can provide some intermediate output files or the examples?

**Comment by zorazrw** [comment]
Hi,

Thanks for your interest!
This is expected for some examples. Our method only filters the potentially useful sentences, if any. 
For example, if you are using the EM metric and no sentence contains the correct answer, then no sentences would be selected, and your output should be an empty string. For the generation model, it means removing all irrelevant contexts and asking the model to predict the answer purely based on its knowledge from training memory.
However, note that for F1 and CXMI metric, you might want to adjust the `threshold` (we used 0.5 and 0.0 for all experiments).
Hope this solves your question!
