### ISSUE TITLE
get_inputs.py on generation task

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [zorazrw/filco#6]
After I have trained the ctx model, I want to get the input to generate the model, so I execute the following script:
python get_inputs.py \
--dataset_path "./datasets/nq/scored/train.json" \
--output_path "./datasets/nq/mgen/em/train_em_top1.json" \
--input_list question filtered --output_list answer \
--n_examples 0 --n_contexts 1 \
--filter_criteria strinc --print_example

But I found a problem, I did not use any output results of my trained ctx model here, is this normal? Or am I doing something wrong?

**Comment by zorazrw** [comment]
Could you explain a bit more on "get the input to generate the model"? Are you trying to "get the input" to the (generation) model, or trying to "generate the model" itself (and which model is this)?
