### ISSUE TITLE
About the training setting

### ISSUE THREAD

**Issue by Hannibal046** [zorazrw/filco#7]
Hi, thanks for the great idea and comprehensive experiments!

I want to ask  if I want to apply FilCo on my own dataset, do I have to do full-parameter tuning on Llama model or just a filtering model with a fixed LLM?

**Comment by zorazrw** [comment]
Thanks for your interest in our work! 
Either way could work! If you have training data that conforms with your test data of interest, you could use our script to train a filtering model.
We also provide a few checkpoints of our filtering models [here](https://huggingface.co/zorazrw), which you could use out-of-the-box. These checkpoints are respectively suitable for open-domain (i.e., Wikipedia) data, multi-hop questions, and special tasks such as fact checking and dialog generation. If your dataset is similar to these domains/types, you can also try directly using our filtering model!
